POST http://localhost:8080/auction
Content-Type: application/json
Host: localhost:8080

{
    "product_name":"rodo",
    "category":"limpeza",
    "description":"acaba com as poças",
    "condition": 1
}

###
Get http://localhost:8080/auction/1eedf4f0-7a09-46cb-824b-ca89cb8261ff
Content-Type: application/json

###
Get http://localhost:8080/auction?status=0
Content-Type: application/json

###
POST http://localhost:8080/bid
Content-Type: application/json
Host: localhost:8080

{
    "user_id":"1eedf4f0-7a09-46cb-824b-ca89cb8263ff",
    "auction_id":"1eedf4f0-7a09-46cb-824b-ca89cb8261ff",
    "amount": 17.36  
}

###
Get http://localhost:8080/auction/winner/1eedf4f0-7a09-46cb-824b-ca89cb8261ff
Content-Type: application/json

###
Get http://localhost:8080/bid/1eedf4f0-7a09-46cb-824b-ca89cb8261ff
Content-Type: application/json
