POST http://localhost:8080/auction
Content-Type: application/json
Host: localhost:8080

{
    "product_name":"vassoura",
    "category":"limpeza",
    "description":"varre tudo que tiver pela frente",
    "condition": 1
}

###
Get http://localhost:8080/auction/5c055b43-1cb5-4239-a5a0-41cb83374510
Content-Type: application/json

###
Get http://localhost:8080/auction?status=0
Content-Type: application/json

###
POST http://localhost:8080/bid
Content-Type: application/json
Host: localhost:8080

{
    "user_id":"1eedf4f0-7a09-46cb-824b-ca89cb8263f5",
    "auction_id":"5c055b43-1cb5-4239-a5a0-41cb83374510",
    "amount": 16.79  
}

###
Get http://localhost:8080/auction/winner/5c055b43-1cb5-4239-a5a0-41cb83374510
Content-Type: application/json

###
Get http://localhost:8080/bid/5c055b43-1cb5-4239-a5a0-41cb83374510
Content-Type: application/json
